### ISSUE TITLE
`FOR UPDATE` and `FOR NO KEY UPDATE ` Examples

### ISSUE THREAD

**Issue by kataklinger** [leontrolski/pglockpy#1]
Hey Russell, I just found your page about Postgres locks and it looks awesome in it is really useful. Thank you for creating it.

I do have some questions/suggestions regarding the examples for `FOR UPDATE` and `FOR NO KEY UPDATE `.

[Your page](https://leontrolski.github.io/pglockpy.html) states following statements take `FOR UPDATE` lock:

- `SELECT * FROM t FOR UPDATE`
- `DELETE FROM`

However in Postgres documentation we can find this:

> The `FOR UPDATE` lock mode is also acquired by [..] an `UPDATE` that modifies the values of certain columns. Currently, the set of columns considered for the `UPDATE` case are those that have a unique index on them that can be used in a foreign key (so partial indexes and expressional indexes are not considered), but this may change in the future.

So it seems that the page is missing this statement from the list:

 - `UPDATE t SET id = 1`

When `id` is column is **part of a unique index** (eg. a primary key).

This statement is actually filed under `FOR NO KEY UPDATE` on your page. Even though the example is correct considering the schema (`id` does have an index, but it is non-unique) it can mislead reader not familiar with it. It is reasonable to assume that column named `id` would be a primary key of a table and under that assumption, update would acquire `FOR UPDATE` lock when the column value is being updated.

**Comment by leontrolski** [comment]
Great spot, thanks for looking at it in detail. I'm Busy at the moment, but will try get a fix in on Monday, thanks again!

**Comment by leontrolski** [comment]
I think I agree with your reading of the docs. I may be doing something dumb in the setup, but I [can't reproduce](https://github.com/leontrolski/pglockpy/pull/2/files#diff-55ec90eaa7b0501ebb17a46f18b8104765c9dcb385dd5b76b91f3bb477a28effR444).

**Comment by kataklinger** [comment]
Hey @leontrolski, thanks for looking into this.

As I understand you are not getting  `55P03` on the `SELECT ... FOR KEY SHARE NOWAIT` statement in the new test.

This is the output I get using two `psql` sessions. I think it matches your example closely. So, I'm not sure why you wouldn't see the exception 🤔

Session 1:
```
test=# create table v (id int unique);
CREATE TABLE
test=# insert into v (id) values (1);
INSERT 0 1
test=# begin transaction;
BEGIN
test=*# update v set id = 2;
UPDATE 1
test=*#
```

Session 2:
```
test=# \set VERBOSITY verbose
test=# begin transaction;
BEGIN
test=*# select * from v for key share nowait;
ERROR:  55P03: could not obtain lock on row in relation "v"
LOCATION:  heap_lock_tuple, heapam.c:4708
test=!#
```

Edit: version info - `psql (15.1, server 15.2)`

**Comment by leontrolski** [comment]
I'm not sure what I was doing before, but it works now 🤷 - again thanks for your help - you get a namecheck in the "sources" :-)
